AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mail Sender Microservice

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        SPRING_PROFILES_ACTIVE: aws

Resources:
  MailSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.jpdevs.mailsender.LambdaHandler::handleRequest
      Runtime: java17
      CodeUri: ./
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref ApiGatewayApi
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          SPRING_MAIN_WEB_APPLICATION_TYPE: servlet

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET','POST','PUT','DELETE','OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        BinaryMediaTypes:
          - 'application/javascript'
          - 'text/javascript'
          - 'application/x-javascript'
          - 'text/css'
          - 'text/html'
          - 'image/png'
          - 'image/jpeg'
          - 'image/gif'

Outputs:
  ApiURL:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"